name: Test Workflow
on: [push, workflow_dispatch]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run tests
        run: ./gradlew test
  Build:
    needs: Test # it will be run after test job, we can use a list of jobs here.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build App
        uses: sparkfabrik/android-build-action@v1.0.0
        with:
          project-path: ./
          output-path: my-app.apk